-- =========================================================
-- Assignment 5: Package Development
-- Purpose:
-- Organize multiple ETL procedures, implement exception
-- handling, and create an error logging framework.
-- =========================================================


-- =========================================================
-- 1. Create ETL Package Schema
-- Purpose:
-- Create a dedicated schema to group all ETL procedures
-- and error logging objects.
-- =========================================================

CREATE SCHEMA IF NOT EXISTS etl_package;


-- =========================================================
-- 2. Create Error Logging Table
-- Purpose:
-- Store information about errors that occur during
-- the execution of ETL procedures.
-- =========================================================

CREATE TABLE etl_package.error_log (
    error_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    procedure_name VARCHAR(100),
    error_message TEXT,
    error_sqlstate VARCHAR(10),
    error_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Check the error log table.
-- Initially, the table should contain no error records.
SELECT *
FROM etl_package.error_log;



-- =========================================================
-- 3. Create Error Logging Procedure
-- Purpose:
-- Provide a reusable procedure for recording errors
-- generated by other ETL procedures.
-- =========================================================

CREATE OR REPLACE PROCEDURE etl_package.log_error(
    p_procedure_name VARCHAR,
    p_error_message TEXT,
    p_error_sqlstate VARCHAR
)
LANGUAGE plpgsql
AS '
BEGIN

    -- Insert error details into the error log table.
    INSERT INTO etl_package.error_log (
        procedure_name,
        error_message,
        error_sqlstate
    )
    VALUES (
        p_procedure_name,
        p_error_message,
        p_error_sqlstate
    );

END;
';


-- =========================================================
-- 4. Test the Error Logging Procedure
-- Purpose:
-- Insert a sample error to verify that log_error()
-- correctly stores error information.
-- =========================================================

CALL etl_package.log_error(
    'test_procedure',
    'This is a test error',
    'TEST01'
);


-- Verify that the test error was successfully recorded.
SELECT *
FROM etl_package.error_log
ORDER BY error_id;



-- =========================================================
-- 5. Exception Handling Test Procedure
-- Purpose:
-- Generate an intentional error and demonstrate how
-- EXCEPTION handling can automatically capture and
-- log the error.
-- =========================================================

CREATE OR REPLACE PROCEDURE etl_package.test_exception()
LANGUAGE plpgsql
AS '
BEGIN

    -- Generate an intentional error for testing.
    RAISE EXCEPTION ''Test ETL failure'';

EXCEPTION
    WHEN OTHERS THEN

        -- Capture the error message and SQLSTATE,
        -- then send them to the error logging procedure.
        CALL etl_package.log_error(
            ''test_exception'',
            SQLERRM,
            SQLSTATE
        );

END;
';


-- Execute the exception test procedure.
-- The generated error will be caught and logged automatically.
CALL etl_package.test_exception();


-- Verify that the automatically captured error
-- was added to the error log table.
SELECT *
FROM etl_package.error_log
ORDER BY error_id;



-- =========================================================
-- 6. Full Load Procedure
-- Purpose:
-- Perform a complete refresh of the Silver Layer by
-- truncating existing data and reloading all records
-- from the Raw Layer.
-- =========================================================

CREATE OR REPLACE PROCEDURE etl_package.full_load_silver()
LANGUAGE plpgsql
AS '
BEGIN

    -- Remove all existing records from Silver tables
    -- before performing the full reload.
    TRUNCATE TABLE
        silver_schema.fact_sales,
        silver_schema.dim_customer,
        silver_schema.dim_product,
        silver_schema.dim_country;


    -- Load the Country Dimension from the Raw Layer.
    INSERT INTO silver_schema.dim_country (
        country_code,
        country_name,
        region
    )
    SELECT
        country_code,
        country_name,
        region
    FROM raw_schema.country;


    -- Load the Customer Dimension from the Raw Layer.
    INSERT INTO silver_schema.dim_customer (
        customer_id,
        customer_name,
        country_code,
        customer_type
    )
    SELECT
        customer_id,
        customer_name,
        country_code,
        customer_type
    FROM raw_schema.customer;


    -- Load the Product Dimension from the Raw Layer.
    INSERT INTO silver_schema.dim_product (
        product_id,
        product_name,
        category,
        standard_price
    )
    SELECT
        product_id,
        product_name,
        category,
        standard_price
    FROM raw_schema.product;


    -- Load all sales transactions into the Sales Fact table.
    INSERT INTO silver_schema.fact_sales (
        transaction_id,
        transaction_date,
        customer_id,
        product_id,
        quantity,
        unit_price,
        total_amount,
        payment_mode
    )
    SELECT
        transaction_id,
        transaction_date,
        customer_id,
        product_id,
        quantity,
        unit_price,
        total_amount,
        payment_mode
    FROM raw_schema.sales_transactions;


-- Handle any error that occurs during the full load.
EXCEPTION
    WHEN OTHERS THEN

        -- Automatically record the procedure name,
        -- error message, and SQLSTATE.
        CALL etl_package.log_error(
            ''full_load_silver'',
            SQLERRM,
            SQLSTATE
        );

END;
';



-- =========================================================
-- 7. Incremental Load Procedure
-- Purpose:
-- Load only new sales transactions from Raw to Silver
-- without deleting or reloading existing records.
-- =========================================================

CREATE OR REPLACE PROCEDURE etl_package.incremental_load_fact_sales()
LANGUAGE plpgsql
AS '
BEGIN

    -- Insert sales transactions into Silver.
    INSERT INTO silver_schema.fact_sales (
        transaction_id,
        transaction_date,
        customer_id,
        product_id,
        quantity,
        unit_price,
        total_amount,
        payment_mode
    )
    SELECT
        r.transaction_id,
        r.transaction_date,
        r.customer_id,
        r.product_id,
        r.quantity,
        r.unit_price,
        r.total_amount,
        r.payment_mode
    FROM raw_schema.sales_transactions r

    -- Only select transactions that do not already
    -- exist in the Silver fact table.
    WHERE NOT EXISTS (
        SELECT 1
        FROM silver_schema.fact_sales s
        WHERE s.transaction_id = r.transaction_id
    );


-- Handle any error that occurs during incremental loading.
EXCEPTION
    WHEN OTHERS THEN

        -- Automatically record the error details.
        CALL etl_package.log_error(
            ''incremental_load_fact_sales'',
            SQLERRM,
            SQLSTATE
        );

END;
';



-- =========================================================
-- 8. MERGE Procedure
-- Purpose:
-- Synchronize sales transactions between Raw and Silver.
--
-- Existing transaction -> UPDATE
-- New transaction      -> INSERT
-- =========================================================

CREATE OR REPLACE PROCEDURE etl_package.merge_fact_sales()
LANGUAGE plpgsql
AS '
BEGIN

    -- Compare Raw transactions with existing Silver records
    -- using transaction_id as the matching key.
    MERGE INTO silver_schema.fact_sales AS s
    USING raw_schema.sales_transactions AS r
        ON s.transaction_id = r.transaction_id


    -- If the transaction already exists in Silver,
    -- update it using the latest values from Raw.
    WHEN MATCHED THEN
        UPDATE SET
            transaction_date = r.transaction_date,
            customer_id      = r.customer_id,
            product_id       = r.product_id,
            quantity         = r.quantity,
            unit_price       = r.unit_price,
            total_amount     = r.total_amount,
            payment_mode     = r.payment_mode


    -- If the transaction does not exist in Silver,
    -- insert it as a new transaction.
    WHEN NOT MATCHED THEN
        INSERT (
            transaction_id,
            transaction_date,
            customer_id,
            product_id,
            quantity,
            unit_price,
            total_amount,
            payment_mode
        )
        VALUES (
            r.transaction_id,
            r.transaction_date,
            r.customer_id,
            r.product_id,
            r.quantity,
            r.unit_price,
            r.total_amount,
            r.payment_mode
        );


-- Handle any error generated during the MERGE operation.
EXCEPTION
    WHEN OTHERS THEN

        -- Automatically record the MERGE error
        -- using the central error logging procedure.
        CALL etl_package.log_error(
            ''merge_fact_sales'',
            SQLERRM,
            SQLSTATE
        );

END;
';



-- =========================================================
-- 9. Validate Package Procedures
-- Purpose:
-- Verify that all procedures were successfully created
-- inside the etl_package schema.
-- =========================================================

SELECT
    routine_name,
    routine_type
FROM information_schema.routines
WHERE routine_schema = 'etl_package'
ORDER BY routine_name;